# Site settings
title: عمر العيثاوي
email: i@omardo.com
description: > # this means to ignore newlines until "baseurl:"
 مدونة عمر العيثاوي، أفكاري، وبعضاً مما أصنع!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.omardo.com" # the base hostname & protocol for your site
github_username:  OmarIthawi

# Build settings
markdown: kramdown
